#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Make sure that servers are configured with the right hostnames

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 511088-web-01 34.229.254.200:80 check
        server 511088-web-02 100.25.47.145:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
